#!/bin/bash

MODE=$1
CONT=$2
PORT=$3

if [[ ${MODE} = 'restart' ]]
then 
    docker stop "$CONT"
    docker container rm "$CONT"
    docker build --rm -t "$CONT":latest .
    docker run -d -e AGENT_NAME="$CONT" -e PORT="$PORT" --name "$CONT" --network=mynet -p "$PORT":"$PORT" "$CONT"
elif [[ ${MODE} = 'enter' ]]
then
    docker exec -it "$CONT" /bin/bash
elif [[ ${MODE} = 'logs' ]]
then
    docker logs "$CONT"
fi



