#!/bin/bash

MODE=$1
AGENT_NAME=$2

if [[ ${MODE} = 'restart' ]]
then

    AGENT_URL=$3
    PORT=$4
    TRACKER_HOST=$5
    NETWORK=$6
    REBUILD=$7

    docker stop "$AGENT_NAME"
    docker container rm "$AGENT_NAME"
    if [[ ${REBUILD} = 'rebuild' ]]
    then
        docker build --rm -t bitz_agent:latest .
    fi
    docker run -d -e AGENT_NAME="$AGENT_NAME" \
                  -e PORT="$PORT" \
                  -e AGENT_URL="$AGENT_URL" \
                  -e TRACKER_HOST="$TRACKER_HOST" \
                  --name "$AGENT_NAME" \
                  --network="$NETWORK" \
                  -p "$PORT":"$PORT" \
                  bitz_agent:latest

elif [[ ${MODE} = 'enter' ]]
then
    docker exec -it "$AGENT_NAME" /bin/bash
elif [[ ${MODE} = 'logs' ]]
then
    docker exec -it "$AGENT_NAME" "/app/infra/get_logs.sh"
elif [[ ${MODE} = 'register' ]]
then

    AGENT_URL=$3
    PORT=$4
    TRACKER_HOST=$5
    curl -X GET  "http://${TRACKER_HOST}:3000/register_agent?agent_name=${AGENT_NAME}&agent_url=${AGENT_URL}&agent_port=${PORT}"

elif [[ ${MODE} = 'unregister' ]]
then
    AGENT_URL=$3
    PORT=$4
    TRACKER_HOST=$5
    curl -X GET  "http://${TRACKER_HOST}:3000/unregister_agent?agent_name=${AGENT_NAME}"
fi



